stages:
  - lint

eslint:
  stage: lint
  image: node:14.17.0-alpine
  variables:
    NODE_VERSION: 14.17.0
  script:
    - npm install
    - npm run lint
prettier:
  stage: lint
  image: node:14.17.0-alpine
  variables:
    NODE_VERSION: 14.17.0
  script:
    - npm install
    - npm run check:format
